[project]
name = "cams2csv"
version = "0.1.0"
description = "A simple tool to extract CAMS PDF data into CSV file"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "pdfplumber>=0.11.7",
    "pyinstaller>=6.17.0",
    "pyqt6>=6.10.0",
]
